### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by UbuntuStrike** [1N3/Sn1per#92] opened 2017-08-19 15:00 UTC
Thanks for the work you put into this and all the other great crowdsheild tools, this is such an amazing recon tool but is there any plan to have a set proxy option?

**Comment by 1N3** [comment] 2017-08-19 16:17
hey, thanks for the feedback and glad you like the tools. I can definitely look into this but it will require some work to implement properly. I'll leave this open while I look into the options. privoxy and proxychains should be able to proxy the traffic through TOR or some other proxy pretty easily.

**Comment by UbuntuStrike** [comment] 2017-08-20 16:24
hey , thanks for the quick reply ! Yeah I figure it'd take a bit of work and I may look into it myself and report back although as I'm sure you are , I'm short on free time. yes I have custom script for tor to set transparent proxy with socks5 forward privoxy and the issue itself isn't sniper perse but the way nmap and tor interact, often I run JonDo as well to exit out of tor as I never get blocked like nmap does exiting out of tor where ass jondo runs on 127.0.0.1 :4001. for examoe with nikto I'd use the --use-proxy flag where I have it set in the config. anyhow I do appreciate the reply and we'll see how it plays out. Thank you

**Comment by UbuntuStrike** [comment] 2017-08-21 02:11
I have a temporary workaround for my situation with that if anyone else finds helpful is very easy to deploy and that was to simply add " --proxy http://127.0.0.1:4001 " to every instance of nmap, no more false closed ports !

**Comment by ChrisFernandez** [comment] 2017-08-21 06:01
I will be interested in adding proxy support as well.. at the moment adding blackarch support will create a pullrequest when rdy.

**Comment by 1N3** [comment] 2018-01-07 20:48
This is a duplicate of https://github.com/1N3/Sn1per/issues/7. Closing this bug out.

**Closed by 1N3** 2018-01-07 20:48 UTC
Labels: duplicate, enhancement
