### ISSUE TITLE
Sn1per Opens Everything In Firefox

### ISSUE THREAD

**Issue by tanujboy** [1N3/Sn1per#51] opened 2017-02-17 10:48 UTC
I'm on Kali 2016.2 with all the latest updates.

Sn1per says "[Running Google Hacking Queries]" and then opens every link in Firefox.

This is how it does it:

1) It opens a URL in Firefox.
2) I close Firefox.
3) It opens another URL again.

Is this normal?

**Comment by 1N3** [comment] 2017-02-17 15:32
This is normal except for having to re-launch firefox each time. The cause for this is usually closing the initial firefox window too early before it loads the other tabs.

Basically, try re-running again but let firefox load completely first (it will load a blank page to start which is normal). There's a short delay after but it should load a few tabbed windows with results. There's 2 parts to the script here, so there's a small delay again which will load the remaining firefox tabs. After everything is loaded and you've reviewed the results, you can just close the main firefox program to quit.

Hope that helps.

**Comment by 1N3** [comment] 2017-02-21 15:28
Closing out for now. Let me know if you need anything else.

**Closed by 1N3** 2017-02-21 15:28 UTC
