### ISSUE TITLE
sniper.conf more docs?

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#226] opened 2019-09-18 19:15 UTC
7.2 Pro and trying to understand the .conf options a little more. While I know 0 and 1 toggle on and off but just would like to know a little more of what some are and didn't see on website and docs about them.

VERBOSE="0" What makes it verbose? Will this give more reportable stuff or debugging type?
AUTOBRUTE="0" I take it this is only for Nuke?
FULLNMAPSCAN="0" Is this different than -fp?
OSINT="0" Wouldn't the -O switch enable this?
ENABLE_AUTO_UPDATES="1" I don't believe I have seen this auto-update?
ONLINE="1" Rem'd out on mine ?
REPORT="1" I believe this will not generate the report which can be done manually?
LOOT="1" Does this report on loot found (creds, etc)?
SNIPER_PRO_CONSOLE_OUTPUT="0" ?
SN1PER_AUTOLOAD="1" ?

ARACHNI_SCAN="1" Any additional setup for this like Burp Pro?

Thanks for the great product! Just trying to get all out of it.

**Comment by 1N3** [comment] 2019-09-18 20:53
Looks like this was a duplicate of https://github.com/1N3/Sn1per/issues/225, so closing this one out.

**Closed by 1N3** 2019-09-18 20:53 UTC
Labels: duplicate
