### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by ProfDrPikachu** [1N3/Sn1per#107] opened 2017-11-18 18:20 UTC
How do i uninstall it Properly and/or Where is a Uninstaller?

**Comment by 1N3** [comment] 2017-11-18 18:35
In the process of adding this to the main sniper build, but in the meantime, you run the below commands to remove sniper:

```
#!/bin/bash
# Uninstall script for sn1per
#
# VARS
OKBLUE='\033[94m'
OKRED='\033[91m'
OKGREEN='\033[92m'
OKORANGE='\033[93m'
RESET='\e[0m'

echo -e "$OKRED                ____               $RESET"
echo -e "$OKRED    _________  /  _/___  ___  _____$RESET"
echo -e "$OKRED   / ___/ __ \ / // __ \/ _ \/ ___/$RESET"
echo -e "$OKRED  (__  ) / / // // /_/ /  __/ /    $RESET"
echo -e "$OKRED /____/_/ /_/___/ .___/\___/_/     $RESET"
echo -e "$OKRED               /_/                 $RESET"
echo -e "$RESET"
echo -e "$OKORANGE + -- --=[http://crowdshield.com$RESET"
echo ""

INSTALL_DIR=/usr/share/sniper

echo -e "$OKGREEN + -- --=[This script will uninstall sniper and remove ALL files under $INSTALL_DIR. Are you sure you want to continue?$RESET"
read answer 

rm -Rf /usr/share/sniper/
rm -f /usr/bin/sniper

echo -e "$OKORANGE + -- --=[Done!$RESET"
echo -e "$OKORANGE + -- --=[To run, type 'sniper'! $RESET"
```

**Comment by ProfDrPikachu** [comment] 2017-11-18 18:37
Thank you for the Fast Response!

Im uninstalling it because i tried to use it on my Debian (8) VPS. A Small part worked but it ended with error code 4 and 5. If you need any Logs before i delete it just tell me :)


Any ideas for making it work on my VPS Running Debain?

**Comment by 1N3** [comment] 2017-11-18 18:43
hmm.. it should run fine on Debian in theory since everything uses apt to install/update. If you have any errors, I can definitely take a look but as it stands currently, the script has only been tested on Kali Linux and Ubuntu mostly.

**Comment by ProfDrPikachu** [comment] 2017-11-18 18:44
whats the File you need for maybe helping me?

**Comment by ProfDrPikachu** [comment] 2017-11-18 18:47
i needed to install metaspolit by hand but all other things didnt got installed

**Comment by ProfDrPikachu** [comment] 2017-11-18 18:47
and it looks like it wasnt in the sources.list

**Comment by ProfDrPikachu** [comment] 2017-11-18 19:13
http://prntscr.com/hc6ezo

**Comment by 1N3** [comment] 2017-11-18 19:24
I see the xdg-open errors which is a change I will be making in the next version. The default browser going forward will just be firefox.

I would need to see the full output of running ./install.sh and a sample sniper scan to troubleshoot all issues but I totally understand if you don't have that or can't provide the entire log.

**Comment by ProfDrPikachu** [comment] 2017-11-18 19:45
I like your Project and i will do it :) Just wait a couple hours.

**Comment by ProfDrPikachu** [comment] 2017-11-18 20:23
https://youtu.be/zOaDdEP3030 This is the Link to the Video. its Private. Sorry that its around 20 Mins. At the end it Crashed the SSH and the only fix was to Restart the VPS :/

Please Message me for a Fix and i hope i can Help you with providing you with Informations.

**Comment by 1N3** [comment] 2017-11-19 04:45
Thanks for the feedback and video... I see a few errors that should be fixed in the latest version (v2.9) which is now available. I still noticed some gem install errors in the install.sh that I don't know the cause of but will keep this open to track the issues. I also added an uninstall.sh script to make removal a bit easier.

**Comment by ProfDrPikachu** [comment] 2017-11-19 08:23
At the Start there are errors. Looks like Following packets are not installed. (Maybe not in the Apt-Get Repo)

-xporbe2 (line 1105)
-metagoofil (line 1112)
-dnsenum (line 1115)

And one Bug

[:== Unary operator Expected 
(Line 1224

**Comment by ProfDrPikachu** [comment] 2017-11-19 08:38
Ruby
Hydra
Wafw00f
Whatweb

**Comment by ProfDrPikachu** [comment] 2017-11-19 08:46
Cutycapt is missing. All of the Packs i Told you are missing. Maybe Check them.

**Comment by 1N3** [comment] 2018-03-06 20:35
hey, not sure if I'll have a fix for this anytime soon. The only official supported platform is currently Kali Linux. Outside of this, all other OS's would be more beneficial to use docker instead as it will run on any linux distro.

**Closed by 1N3** 2018-03-06 20:35 UTC
Labels: bug, help wanted
