### ISSUE TITLE
[HEADS UP] Sn1per crashed my system

### ISSUE THREAD

**Issue by tacticalDevC** [1N3/Sn1per#243] opened 2020-01-06 11:02 UTC
So I installed Sn1per and found out that the Kali repositories are mixed without apt pinning. This led to:
- a slower system (REALLY slow)
- a bunch of packages having errors
- not being able to connect to anything because the wifi adapter isn't recognized anymore (without doing some trickery)
- a bunch of programs not starting anymore
... and a few more issues I am not going to mention.

This is just a heads up. Please fix it or many people will have issues like me.

Technical details:
Ubuntu 18.04.3 LTS Bionic Beaver

**Comment by 1N3** [comment] 2020-01-06 15:57
Thanks for the heads up and sorry to hear that. I'll definitely take a look to see if I can reproduce the issue. This was working fine for a while on Ubuntu, but there may have been some changes recently that may have stopped this from working as expected. Will definitely test to confirm and will let you know though!

**Comment by tacticalDevC** [comment] 2020-01-06 19:35
I don't understand much when we talk about apt pinning but as a suggestion for a fix you could download all packages needed in a dedicated folder and start Sn1per with a custom LD_LIBRARY_PATH. You may have to customize the PATH too for the integrated tools. Doing this could prevent the system being corrupted.

**Comment by 1N3** [comment] 2020-01-08 20:09
Thanks for the suggestions. 

I just tested on Ubuntu 18.04.3 LTS Bionic Beaver using a fresh ISO image, installing git (apt install git), cloning Sn1per (git clone https://github.com/1N3/Sn1per) and running (./install.sh). This seemed to work fine and did not receive any errors. Not sure if this is because it's a fresh image or something else, but will look into the options you mentioned to see if that works better.

**Comment by tacticalDevC** [comment] 2020-01-09 05:48
Hmmm that's strange. I ran `install_debian_ubuntu.sh`. That script caused to mix the apt repositories. You just ran `install.sh`, didn't you? If this is right please test again with the other script. I hope I don't steal too much of your time tho :/
Anyway it is a bad idea to mix the repositories of different distributions. I don't blame you. Maybe you just didn't know that.

**Comment by 1N3** [comment] 2020-01-09 15:49
install.sh will basically just run install_debian_ubuntu.sh automatically when Ubuntu is detected, but it's essentially running the same script/code. Regarding the mix of repos across distros, I completely agree and will look at better ways to handle this. This was mainly done because many Kali based tools seem to be missing from the Ubuntu repos for some reason.

**Comment by tacticalDevC** [comment] 2020-01-09 17:34
I'm happy that you can provide a fix :)
Well Kali Linux is a fully fledged pentesting distro. Ubuntu isn't.

**Comment by 1N3** [comment] 2020-07-01 20:02
hey, good news... I've updated the installer to NOT depend on kali repos at all now which should hopefully solve this issue. I also tested on a fresh Ubuntu 18.04 system and seems to work perfectly now. Closing out, but let me know if you still have issues.

**Closed by 1N3** 2020-07-01 20:02 UTC
Labels: bug
