### ISSUE TITLE
sed: can't read /usr/bin/msfdb: No such file or directory

### ISSUE THREAD

**Issue by hktalent** [1N3/Sn1per#215] opened 2019-08-14 05:17 UTC
$ docker build -t sn1per-docker .
```
sed: can't read /usr/bin/msfdb: No such file or directory
The command '/bin/sh -c sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit' returned a non-zero code: 2
```

**Comment by 1N3** [comment] 2019-08-14 15:53
Hi, this is a duplicate of https://github.com/1N3/Sn1per/issues/211 which is still open/pending.

**Closed by 1N3** 2019-08-14 15:53 UTC
Labels: duplicate
