### ISSUE TITLE
NS LookUp IP reversal

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#124] opened 2018-02-14 19:42 UTC
I was scanning an internal web server (here at work) and I noticed that the NSLOOKUP stage switched the IP address I was scanning, specifically the octets. So say if you are scanning 127.0.0.1, it would switch it to 1.0.0.127. I would provide you with screenshots but for obvious reasons I can't.

**Comment by 1N3** [comment] 2018-02-14 19:45
strange... I'll take a look at this but throughout the scan, a global var of $TARGET is used and passed to all tools so I'm not sure what could have caused this.

**Comment by gbiagomba** [comment] 2018-02-14 22:59
I will run it again tonight and I will check if it happens again

**Comment by gbiagomba** [comment] 2018-03-06 20:09
![image](https://user-images.githubusercontent.com/5851606/37055689-551d72ba-2150-11e8-87e8-921c59add1a2.png)

Just so you know version 4 still has it

**Comment by 1N3** [comment] 2018-07-04 15:56
Hi, figured out that this is caused by doing IP reverse lookups via the 'host' command. This is normal and the message here is stating that the reverse IP lookup for 127.0.0.1 is a pointer to 'localhost'. Gonna close this out for now but hope that helps.

**Closed by 1N3** 2018-07-04 15:56 UTC
Labels: bug

**Comment by gbiagomba** [comment] 2018-11-09 15:03
Yes it does thank you
