### ISSUE TITLE
sniper only fully runs as root such is always a bad idea.[suggestion]

### ISSUE THREAD

**Issue by ReK2Fernandez** [1N3/Sn1per#178] opened 2018-10-19 02:40 UTC
Hello a licensed user here of sniper(trying it out) 
A good OpSec person no matter if is kali or Arch or centoOS etc will always run things as user then sudo for certain tasks..and sudo taken to the minimum.  IMO sniper is forced to run as root the whole thing because some nmap scans etc can only run as root, fine. But I seen other scanners even the ones I build that will ask for sudo pass only when is really needed. as in like before nmap, then saves results -oA and chown the file back to user, and continues with the rest as user until sudo is needed again, since password was entered once, unless it has timed out will not be needed.
The problem I'm having is that even if I run sniper the whole thing under sudo, at the end saves all the files as root, not on my home dir but on the system dir(another bad thing) and the site html UI for sniper that I licensed to test, never comes out on my browser because my browser is run as the user not root.. and I don't have a UI on root, I never log in to a UI as root, only user then sudo to root.. makes sense?
can we make it so sniper can be run as a user at least the licensed version please?

Thanks

**Comment by 1N3** [comment] 2018-10-19 15:44
Hi, Thanks for the feedback. All valid points btw. By default, sniper runs all tools as 'root' and saves all files to /usr/share/sniper/. I haven't tried using a different install dir or user but will see how much work is required to do this and will keep you posted. This could introduce tons of issues with how Sn1per was designed, but I think with time, this is achievable.

**Comment by anoncam** [comment] 2019-10-24 16:40
this should be run as `root` in `kalilinux/kali-linux-docker`.  see the `Dockerfile` in this repo.

Also, [this documentation](https://www.tutorialspoint.com/unix/unix-file-permission.htm) should explain Linux/Unix File permissions, should you have to add a `$SVC_USER` or something to allow `=!` `root` access, I suppose.

I'd read up on Kali.  If you bought Sn1per pro it's worth configuring.
https://www.kali.org/kali-linux-documentation/

imo.

**Comment by researchlab17** [comment] 2020-02-05 21:54
Major issues with the new release of "no root" Kali, Pro functionality is almost completely broken cannot make use of browser launch commands, cannot use domain lists ETC. Same result with Parrot.

**Comment by ReK2Fernandez** [comment] 2020-02-08 19:02
I knew this day will come :)  eventually.

**Comment by 1N3** [comment] 2020-02-13 21:08
I'm still trying to find a good solution for this, but in the meantime, you will need to run sniper with sudo (ie. sudo sniper). Sn1per utilizes the metasploit and postgresql services which requires 'root' to run. 

Alternatively, you can always just run 'sudo su' to become root, then run sniper as normal. You can also set a 'root' password on the new Kali by running 'sudo su' and 'passwd root' to set the password and login permanently.

**Comment by researchlab17** [comment] 2020-02-17 19:43
But the Pro options will not work in the browser regardless. Standing by. Using "Old" Kali on another box in the meantime.

**Comment by 1N3** [comment] 2020-02-18 21:23
@researchlab17  I was able to add a fix for this in the latest master branch for Sn1per and tested this on the latest kali 2020.1 release as a normal user with sudo privs running Sn1per Professional 7.0 and everything is working fine now on my end. You still need to run sniper with 'sudo sniper', but it should work the same as before on the latest release.

**Comment by 1N3** [comment] 2020-02-18 21:24
It will be published in v8.2 soon, but you can always just git clone the Sn1per repo and re-run the install.sh to apply the fix if you don't want to wait.

**Comment by researchlab17** [comment] 2020-02-19 15:13
It seems the command was issued through "quick commands" but the results page still shows 

"This site can’t be reached The webpage at https://127.0.0.1:1337/pro/addons/server-scan.php might be temporarily down or it may have moved permanently to a new web address.
ERR_CONTENT_DECODING_FAILED"

Which isn't that big of a deal, just giving some feedback, the important thing is the scan launched. ;)

**Comment by 1N3** [comment] 2020-02-20 19:46
@researchlab17 gotcha. That error you mentioned seems to be a Chrome only error and is a known issue with Chrome. You *should* be able to use firefox though to see the scan status in real time.

**Comment by 1N3** [comment] 2020-04-13 18:22
Closing this out as there doesn't appear to be a good way to avoid using sudo or root perms to run all tools.

**Closed by 1N3** 2020-04-13 18:22 UTC
Labels: enhancement
